<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="1" failed="0" total="2" passed="1">
  <reporter-output>
    <line>
      <![CDATA[fist test pass]]>
    </line>
  </reporter-output>
  <suite name="Data Driven" duration-ms="5583" started-at="2018-05-15T00:15:15Z" finished-at="2018-05-15T00:15:20Z">
    <groups>
    </groups>
    <test name="LoginTest" duration-ms="4095" started-at="2018-05-15T00:15:15Z" finished-at="2018-05-15T00:15:19Z">
      <class name="testcases.LoginTest">
        <test-method status="PASS" signature="loginasBanker()[pri:0, instance:testcases.LoginTest@139982de]" name="loginasBanker" duration-ms="1827" started-at="2018-05-15T05:45:15Z" finished-at="2018-05-15T05:45:17Z">
          <reporter-output>
            <line>
              <![CDATA[fist test pass]]>
            </line>
          </reporter-output>
        </test-method> <!-- loginasBanker -->
      </class> <!-- testcases.LoginTest -->
    </test> <!-- LoginTest -->
    <test name="AddCust" duration-ms="12" started-at="2018-05-15T00:15:20Z" finished-at="2018-05-15T00:15:20Z">
      <class name="testcases.AddCustTest">
        <test-method status="PASS" signature="setUp()[pri:0, instance:testcases.AddCustTest@6ed3ccb2]" name="setUp" is-config="true" duration-ms="60245" started-at="2018-05-15T05:44:15Z" finished-at="2018-05-15T05:45:15Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="SKIP" signature="addcustomer(java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:testcases.AddCustTest@6ed3ccb2]" name="addcustomer" duration-ms="0" started-at="2018-05-15T05:45:20Z" data-provider="dp" finished-at="2018-05-15T05:45:20Z">
          <exception class="java.lang.RuntimeException">
            <message>
              <![CDATA[Can't invoke method public java.lang.Object[][] utilities.TestUtil.getData(java.lang.reflect.Method) on this instance of class testcases.AddCustTest due to class mismatch]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.RuntimeException: Can't invoke method public java.lang.Object[][] utilities.TestUtil.getData(java.lang.reflect.Method) on this instance of class testcases.AddCustTest due to class mismatch
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:75)
	at org.testng.internal.MethodInvocationHelper.invokeDataProvider(MethodInvocationHelper.java:137)
	at org.testng.internal.Parameters.handleParameters(Parameters.java:430)
	at org.testng.internal.Invoker.handleParameters(Invoker.java:1274)
	at org.testng.internal.Invoker.createParameters(Invoker.java:989)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1079)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:295)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:84)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:90)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:203)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:155)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.RuntimeException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- addcustomer -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:testcases.AddCustTest@6ed3ccb2]" name="tearDown" is-config="true" duration-ms="1" started-at="2018-05-15T05:45:20Z" finished-at="2018-05-15T05:45:20Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- testcases.AddCustTest -->
    </test> <!-- AddCust -->
  </suite> <!-- Data Driven -->
</testng-results>
